# run-install-test.cmake
# CMake script that installs obsidian to a temporary prefix, then runs the
# installed executable on the test-cpp include folder.
#
# Expected variables (passed via -D):
#   BUILD_DIR  - Path to the CMake build directory
#   CONFIG     - Build configuration (Debug, Release, etc.)
#   INPUT_DIR  - Path to the test-cpp/include directory
#   OUTPUT_DIR - Directory for obsidian output
#   INC_DIRS         - Comma-separated include directories for obsidian
#   COMPILE_OPTIONS  - (Optional) Comma-separated compile options for obsidian

if (NOT DEFINED BUILD_DIR)
    message(FATAL_ERROR "BUILD_DIR is not defined")
endif ()
if (NOT DEFINED CONFIG)
    message(FATAL_ERROR "CONFIG is not defined")
endif ()
if (NOT DEFINED INPUT_DIR)
    message(FATAL_ERROR "INPUT_DIR is not defined")
endif ()
if (NOT DEFINED OUTPUT_DIR)
    message(FATAL_ERROR "OUTPUT_DIR is not defined")
endif ()

# Determine platform-specific settings.
if (CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
    set(EXE_SUFFIX ".exe")
    set(IS_WINDOWS TRUE)
else ()
    set(EXE_SUFFIX "")
    set(IS_WINDOWS FALSE)
endif ()

set(INSTALL_PREFIX "${OUTPUT_DIR}/install")

# Clean previous install.
file(REMOVE_RECURSE "${INSTALL_PREFIX}")

# Run cmake --install.
execute_process(
    COMMAND ${CMAKE_COMMAND} --install "${BUILD_DIR}" --prefix "${INSTALL_PREFIX}" --config ${CONFIG}
    RESULT_VARIABLE INSTALL_RESULT
)
if (NOT INSTALL_RESULT EQUAL 0)
    message(FATAL_ERROR "cmake --install failed with exit code ${INSTALL_RESULT}")
endif ()

# Verify expected files exist.
if (NOT EXISTS "${INSTALL_PREFIX}/obsidian${EXE_SUFFIX}")
    message(FATAL_ERROR "obsidian${EXE_SUFFIX} not found in install directory")
endif ()
if (IS_WINDOWS AND NOT EXISTS "${INSTALL_PREFIX}/libclang.dll")
    message(FATAL_ERROR "libclang.dll not found in install directory")
endif ()
if (NOT EXISTS "${INSTALL_PREFIX}/include/obs/obs.hpp")
    message(FATAL_ERROR "include/obs/obs.hpp not found in install directory")
endif ()
if (NOT EXISTS "${INSTALL_PREFIX}/LICENSE")
    message(FATAL_ERROR "LICENSE not found in install directory")
endif ()
if (NOT EXISTS "${INSTALL_PREFIX}/LLVM-LICENSE")
    message(FATAL_ERROR "LLVM-LICENSE not found in install directory")
endif ()

# Create output directory for generated files.
set(GEN_OUTPUT "${OUTPUT_DIR}/gen")
file(MAKE_DIRECTORY "${GEN_OUTPUT}")

# Build obsidian arguments.
set(OBSIDIAN_CMD "${INSTALL_PREFIX}/obsidian${EXE_SUFFIX}"
    input-dirs=${INPUT_DIR}
    output-dir=${GEN_OUTPUT}
)
if (DEFINED INC_DIRS)
    list(APPEND OBSIDIAN_CMD inc-dirs=${INC_DIRS})
endif ()
if (DEFINED COMPILE_OPTIONS)
    list(APPEND OBSIDIAN_CMD compile-options=${COMPILE_OPTIONS})
endif ()

# Run the installed obsidian.
execute_process(
    COMMAND ${OBSIDIAN_CMD}
    RESULT_VARIABLE OBSIDIAN_RESULT
)
if (NOT OBSIDIAN_RESULT EQUAL 0)
    message(FATAL_ERROR "Installed obsidian failed with exit code ${OBSIDIAN_RESULT}")
endif ()

# Verify that a reflection header was generated.
if (NOT EXISTS "${GEN_OUTPUT}/reflection.hpp")
    message(FATAL_ERROR "reflection.hpp was not generated by installed obsidian")
endif ()

message(STATUS "Install test passed")
